### PR TITLE
feat: support customization of some options

### PR DESCRIPTION
**Pull request by condorheroblog**

### CODE REVIEW

**Comment by condorheroblog** [comment]
It feels weird without a title in there🤔

image

**Comment by hunghg255** [comment]
> It feels weird without a title in there🤔
> 
> image

=))) I think need to heading 1 (`#`), currently, maybe I am using heading 2 (`##`)

**Comment by condorheroblog** [comment]
This update was merged into the master branch, and now the default branch is main . Which one should we use?

**Comment by hunghg255** [comment]
> This update was merged into the master branch, and now the default branch is main . Which one should we use?

oh sorry, I merge master to main

**Pull request merged**
