### PR TITLE
fix: resolve nested button DOM warning

### PR DESCRIPTION
**Pull request by condorheroblog**
Closed https://github.com/hunghg255/reactjs-tiptap-editor/issues/3

### CODE REVIEW

**Comment by condorheroblog** [comment]
Excuse me, I have a question for you.

Do you have any plans to upgrade ESLint to the latest version(V8)? Or just use this package @antfu/eslint-config.

Have a good  nice day.

**Comment by hunghg255** [comment]
> @antfu/eslint-config

Yes, I also want to use flat config. I see many eslint plugins still not upgraded

**Comment by hunghg255** [comment]
> That's great, and I think we do not need Prettier anymore, but it's all up to you.😉

oke, I will upgarde soon, 
I want to share this. I cloned the emoji extension by download js file from the network on tiptap docs. https://tiptap-emoji.surge.sh/
but because of the license I did a warning so I can not push code to this repo =)))

**Comment by hunghg255** [comment]
If you are interested, I will invite you to the repo

**Comment by condorheroblog** [comment]
Nice, please🥰

**Comment by hunghg255** [comment]
> Nice, please🥰

ok I invited you to repo

**Comment by condorheroblog** [comment]
Thank you very much 🥳

**Pull request merged**
